name: Build

on:
  push:
    branches: ["main"]

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.13.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0

      - name: Building and deploying new website
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /root/website
            git pull 
            docker rm $(docker stop $(docker ps -a -q --filter ancestor=koders-website-v5 --format="{{.ID}}"))
            docker rmi koders-website-v5
            docker build . -t koders-website-v5
            docker run -d -p 8081:3000 --name koders-website-v5 -e ${{ secrets.WEBHOOK_URL }} koders-website-v5
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          pass: ${{ secrets.REMOTE_PASSWORD }}
